# DATASOURCE
spring:
  datasource:
    url:
      jdbc:h2:file:./data/clients
    driverClassName:
      org:
        h2:
          Driver
    username:
      rafess
    password:
      1345

  # H2 Console

  h2:
    console:
      enabled:
        true

      path:
        /h2-console

  # JPA
  jpa:
    database-platform:
      org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto:
        update

kafka:
  topic:
    name:
      com.letscode.topic
server:
  port: 8081
